---
service: newco-contact-us
# app: newco-contact-us
# org: newco-bcg

frameworkVersion: "3"


provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  logs:
    httpApi: true
  httpApi:
    metrics: true
    cors:
      allowedOrigins:
        - https://www.articul8.ai/
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - POST
      allowCredentials: false
      maxAge: 6000
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "arn:aws:ses:us-east-1:754957524886:*"

functions:
  newco-contact-us:
    handler: index.handler
    events:
      - httpApi:
          path: /contact-us
          method: post

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
